service: serverless-nodejs-starter

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment: ${file(env.yml):${self:provider.stage}}

functions:
  test:
    handler: handler.test
    memorySize: 128 # default is 1024
    timeout: 30 # default is 6
#    events:
#      - http:
#          path: hello
#          method: get
